// Code generated by pbr. DO NOT EDIT.

//go:build !pbrinject
// +build !pbrinject

package router

import (
	"github.com/labstack/echo"
	pbr_route "example.com/foo/router_echo/blog"
)

func Build(e *echo.Echo) {
	e.GET("/blog", pbr_route.GET)
}
