// Code generated by routegen. DO NOT EDIT.

//go:generate go run -mod=mod github.com/serkodev/routegen/cmd/routegen
//go:build !routegeninject
// +build !routegeninject

package router

import (
	"github.com/gin-gonic/gin"
	routegen_r "example.com/basic/foo"
	routegen_r2 "example.com/basic/foo/bar"
	routegen_r3 "example.com/basic/foo/bar/baz"
)

func Build(g *gin.Engine) {
	g.GET("/", GET)
	g.GET("/foo", routegen_r.GET)
	g.GET("/foo/bar", routegen_r2.GET)
	g.GET("/foo/bar/baz", routegen_r3.GET)
}

func Run() {
	g := gin.Default()
	Build(g)
	g.Run()
}
