package pbr

import (
	"fmt"
	"go/ast"
	"go/printer"
	"go/token"
	"go/types"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/tools/go/ast/astutil"
	"golang.org/x/tools/go/packages"
)

type gen struct {
	pkg       *packages.Package
	buildFunc map[*ast.FuncDecl]bool
}

func newGen(pkg *packages.Package, buildFunc map[*ast.FuncDecl]bool) *gen {
	return &gen{
		pkg:       pkg,
		buildFunc: buildFunc,
	}
}

func Load() error {
	wd, err := os.Getwd()
	if err != nil {
		fmt.Println("failed to get working directory: ", err)
		return err
	}
	fmt.Println(wd)

	cfg := &packages.Config{
		// Context:    ctx,
		Mode: packages.NeedName | packages.NeedFiles | packages.NeedCompiledGoFiles | // LoadFiles
			packages.NeedImports | // LoadImports
			packages.NeedTypes | packages.NeedTypesSizes | // LoadTypes
			packages.NeedSyntax | packages.NeedTypesInfo | // LoadSyntax
			packages.NeedDeps, // LoadTypes
		Dir: wd,
		// Env:        env,
		BuildFlags: []string{"-tags=pbrinject"},
		// TODO(light): Use ParseFile to skip function bodies and comments in indirect packages.
	}

	pkgs, err := packages.Load(cfg)
	if err != nil {
		return err
	}

	for _, pkg := range pkgs {
		fmt.Println("path", pkg.PkgPath)

		for _, f := range pkg.Syntax {
			buildFuncs := make(map[*ast.FuncDecl]bool)

			ast.Inspect(f, func(n ast.Node) bool {
				fn, ok := n.(*ast.FuncDecl)
				if !ok {
					return true
				}

				if buildCall, err := findInjectorBuild(pkg.TypesInfo, fn); err != nil {
					fmt.Println("findInjectorBuild error", err.Error())
					return true
				} else if buildCall != nil {
					// inject build found
					buildFuncs[fn] = true
				}
				return true
			})

			if len(buildFuncs) > 0 {
				r := newRouteGen()
				routes := r.parseRoute(wd)

				g := newGen(pkg, buildFuncs)
				g.inject(f, routes)
			}
		}
	}

	return nil
}

func (g *gen) generate(f *ast.File) error {
	oriFilePath := g.pkg.Fset.File(f.Pos()).Name()

	filename := filepath.Base(oriFilePath)
	ext := strings.ToLower(filepath.Ext(filename))
	nonExt := filename[:len(filename)-len(ext)]
	dir := filepath.Dir(oriFilePath)
	outputPath := dir + "/" + nonExt + "_gen" + ext

	out, err := os.Create(outputPath)
	if err != nil {
		return err
	}
	defer out.Close()

	out.WriteString("// Code generated by pbr. DO NOT EDIT.\n")
	out.WriteString("\n")
	out.WriteString("//go:build !pbrinject\n")
	out.WriteString("// +build !pbrinject\n")
	out.WriteString("\n")
	out.WriteString("package " + g.pkg.Name + "\n")
	out.WriteString("\n")

	for i, decl := range f.Decls {
		printAST(token.NewFileSet(), decl)
		fmt.Print("\n")

		if err := printer.Fprint(out, token.NewFileSet(), decl); err != nil {
			return err
		}

		if i < len(f.Decls)-1 {
			out.WriteString("\n\n")
		} else {
			out.WriteString("\n") // EOF
		}
	}

	return nil
}

func (g *gen) importsFromRoutes(routes []*RoutePackage, n *namer) []*ast.ImportSpec {
	var specs []*ast.ImportSpec

	// TODO: check original imported pkg
	for _, r := range routes {
		if r.RelativePath != "." {
			newName := n.gen("pbr_route")
			spec := &ast.ImportSpec{
				Path: &ast.BasicLit{
					Kind:  token.STRING,
					Value: `"` + r.PkgPath + `"`,
				},
				Name: ast.NewIdent(newName),
			}
			r.importSpec = spec
			specs = append(specs, spec)
		}
		if len(r.SubPackages) > 0 {
			specs = append(specs, g.importsFromRoutes(r.SubPackages, n)...)
		}
	}

	return specs
}

func (g *gen) inject(f *ast.File, routes []*RoutePackage) {
	scopes := make([]*types.Scope, len(g.buildFunc))
	for fn := range g.buildFunc {
		scopes = append(scopes, g.pkg.TypesInfo.Scopes[fn.Type])
	}
	n := newNamerWithScopes(scopes)
	specs := g.importsFromRoutes(routes, n)

	astutil.Apply(f, func(c *astutil.Cursor) bool {
		// inject imports
		if imp, ok := c.Node().(*ast.ImportSpec); ok {
			if imp.Path.Value == `"github.com/serkodev/pbr"` {
				// for i := len(routes) - 1; i >= 0; i-- {
				// 	routeImp := routes[i]
				// 	if routeImp.importSpec != nil {
				// 		c.InsertAfter(routeImp.importSpec)
				// 	}
				// }
				for i := len(specs) - 1; i >= 0; i-- {
					c.InsertAfter(specs[i])
				}
				c.Delete()
			}
		} else if fn, ok := c.Node().(*ast.FuncDecl); ok {
			if g.buildFunc[fn] {
				g.injectFunction(fn, routes)
			}
		}
		return true
	}, nil)

	g.generate(f)
}

func (g *gen) injectFunction(fn *ast.FuncDecl, routes []*RoutePackage) error {
	astutil.Apply(fn.Body, func(c *astutil.Cursor) bool {
		if stmt, ok := c.Node().(ast.Stmt); ok {
			if s := getInjectorStmt(g.pkg.TypesInfo, stmt); s != nil {
				ident := s.Args[0].(*ast.Ident)
				scope := g.pkg.TypesInfo.Scopes[fn.Type]
				n := newNamer(scope)
				for _, stmt := range injectPkgRoute(ident, routes, n) {
					c.InsertBefore(stmt)
				}
				c.Delete()
			}
		}
		return true
	}, nil)
	// printAST(token.NewFileSet(), fn.Body)

	return nil
}

func injectPkgRoute(ident *ast.Ident, routes []*RoutePackage, n *namer) []ast.Stmt {
	var stmts []ast.Stmt

	for _, route := range routes {
		rIdent := ident

		imp := ""
		if routeImport := route.importSpec; routeImport != nil {
			imp = routeImport.Name.Name
		}

		routePath := route.routePath()
		hasMiddleware := route.hasMiddleware()

		if hasMiddleware {
			groupVal := n.gen("grp")
			stmts = append(stmts, mustParseExprF(`%s := %s.Group("%s")`, groupVal, ident.Name, routePath))

			rIdent = ast.NewIdent(groupVal)
			routePath = "" // set for root route path
		}

		if rstmts := injectSels(rIdent, route.Sels, imp, routePath); len(rstmts) > 0 {
			stmts = append(stmts, rstmts...)
		}

		for _, rs := range route.SubRoutes {
			if rs.Sub == "" {
				panic("sub route Sub should not empty")
			}

			// sub
			typeVar := n.gen(strings.ToLower(rs.Sub))
			sub := rs.Sub
			if imp != "" {
				sub = imp + "." + sub
			}
			stmts = append(stmts, mustParseExprF(`%s := &%s{}`, typeVar, sub))

			routePath := getRoutePath(routePath, rs.Path)

			if rstmts := injectSels(rIdent, rs.Sels, typeVar, routePath); len(rstmts) > 0 {
				stmts = append(stmts, rstmts...)
			}
		}

		// sub packages
		if hasMiddleware {
			stmts = append(stmts, injectPkgRoute(rIdent, route.SubPackages, n)...)
		}
	}

	return stmts
}

func injectSels(ident *ast.Ident, sels []string, typeVar string, routePath string) []ast.Stmt {
	var stmts []ast.Stmt

	for _, sel := range sels {
		var routeSel = sel
		if typeVar != "" {
			routeSel = typeVar + "." + routeSel
		}

		if sel == "Middleware" {
			stmts = append(stmts, mustParseExprF(`%s.Use(%s)`, ident.Name, routeSel))
		} else {
			stmts = append(stmts, mustParseExprF(`%s.%s("%s", %s)`, ident.Name, sel, routePath, routeSel))
		}
	}

	return stmts
}
