// Code generated by routegen. DO NOT EDIT.

//go:generate go run -mod=mod github.com/serkodev/routegen/cmd/routegen
//go:build !routegeninject
// +build !routegeninject

package middleware

import (
	"github.com/gin-gonic/gin"
	routegen_r "example.com/middleware/foo"
)

func Build(g *gin.Engine) {
	grp := g.Group("/")
	{
		grp.Use(Middleware)
		grp2 := grp.Group("/bar")
		{
			bar := &Bar{}
			grp2.Use(bar.Middleware)
			grp2.GET("", bar.GET)
			grp3 := grp.Group("/foo")
			{
				grp3.Use(routegen_r.Middleware)
				grp3.GET("", routegen_r.GET)
			}
		}
	}
}
