// Code generated by routegen. DO NOT EDIT.

//go:build !routegeninject
// +build !routegeninject

package router

import (
	"github.com/gin-gonic/gin"
	routegen_r "example.com/wildcard/any/_"
	routegen_r2 "example.com/wildcard/named/_id"
)

func Build(g *gin.Engine) {
	g.GET("/any/*", routegen_r.GET)
	g.GET("/named/:id", routegen_r2.GET)
}
