// Code generated by routegen. DO NOT EDIT.

//go:generate go run -mod=mod github.com/serkodev/routegen/cmd/routegen
//go:build !routegeninject
// +build !routegeninject

package router

import (
	"github.com/labstack/echo"
	routegen_r "example.com/foo/blog"
)

func Build(e *echo.Echo) {
	e.GET("/blog", routegen_r.GET)
}
