// Code generated by routegen. DO NOT EDIT.

//go:generate go run -mod=mod github.com/serkodev/routegen/cmd/routegen
//go:build !routegeninject
// +build !routegeninject

package router

import (
	"github.com/gin-gonic/gin"
	routegen_r "example.com/alias/foo"
)

func Build(g *gin.Engine) {
	bar := &routegen_r.Bar{}
	g.GET("/foo/bar-alias", bar.GET)
	baz := &routegen_r.Baz{}
	g.GET("/foo/baz-alias", baz.GET)
}
