// Code generated by routegen. DO NOT EDIT.

//go:build !routegeninject
// +build !routegeninject

package router

import (
	"github.com/gin-gonic/gin"
	routegen_r "example.com/subroute/foo"
)

func Build(g *gin.Engine) {
	g.GET("/foo", routegen_r.GET)
	bar := &routegen_r.Bar{}
	g.GET("/foo/bar", bar.GET)
	baz := &routegen_r.Baz{}
	g.GET("/foo/baz", baz.GET)
}
